// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: proto/calculator.proto

package calculator

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_proto_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *AddRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           float64                `protobuf:"fixed64,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_proto_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetRes() float64 {
	if x != nil {
		return x.Res
	}
	return 0
}

type SubRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubRequest) Reset() {
	*x = SubRequest{}
	mi := &file_proto_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubRequest) ProtoMessage() {}

func (x *SubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubRequest.ProtoReflect.Descriptor instead.
func (*SubRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *SubRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SubRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           float64                `protobuf:"fixed64,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubResponse) Reset() {
	*x = SubResponse{}
	mi := &file_proto_calculator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubResponse) ProtoMessage() {}

func (x *SubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubResponse.ProtoReflect.Descriptor instead.
func (*SubResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *SubResponse) GetRes() float64 {
	if x != nil {
		return x.Res
	}
	return 0
}

type MultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultRequest) Reset() {
	*x = MultRequest{}
	mi := &file_proto_calculator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultRequest) ProtoMessage() {}

func (x *MultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultRequest.ProtoReflect.Descriptor instead.
func (*MultRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{4}
}

func (x *MultRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MultRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type MultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           float64                `protobuf:"fixed64,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultResponse) Reset() {
	*x = MultResponse{}
	mi := &file_proto_calculator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultResponse) ProtoMessage() {}

func (x *MultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultResponse.ProtoReflect.Descriptor instead.
func (*MultResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{5}
}

func (x *MultResponse) GetRes() float64 {
	if x != nil {
		return x.Res
	}
	return 0
}

type DivRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DivRequest) Reset() {
	*x = DivRequest{}
	mi := &file_proto_calculator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DivRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivRequest) ProtoMessage() {}

func (x *DivRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivRequest.ProtoReflect.Descriptor instead.
func (*DivRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{6}
}

func (x *DivRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *DivRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type DivResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           float64                `protobuf:"fixed64,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DivResponse) Reset() {
	*x = DivResponse{}
	mi := &file_proto_calculator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DivResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DivResponse) ProtoMessage() {}

func (x *DivResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DivResponse.ProtoReflect.Descriptor instead.
func (*DivResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{7}
}

func (x *DivResponse) GetRes() float64 {
	if x != nil {
		return x.Res
	}
	return 0
}

type SqrtRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqrtRequest) Reset() {
	*x = SqrtRequest{}
	mi := &file_proto_calculator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqrtRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqrtRequest) ProtoMessage() {}

func (x *SqrtRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqrtRequest.ProtoReflect.Descriptor instead.
func (*SqrtRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{8}
}

func (x *SqrtRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

type SqrtResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           float64                `protobuf:"fixed64,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SqrtResponse) Reset() {
	*x = SqrtResponse{}
	mi := &file_proto_calculator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SqrtResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SqrtResponse) ProtoMessage() {}

func (x *SqrtResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SqrtResponse.ProtoReflect.Descriptor instead.
func (*SqrtResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{9}
}

func (x *SqrtResponse) GetRes() float64 {
	if x != nil {
		return x.Res
	}
	return 0
}

type PercentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Percent       float64                `protobuf:"fixed64,2,opt,name=percent,proto3" json:"percent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PercentRequest) Reset() {
	*x = PercentRequest{}
	mi := &file_proto_calculator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PercentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PercentRequest) ProtoMessage() {}

func (x *PercentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PercentRequest.ProtoReflect.Descriptor instead.
func (*PercentRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{10}
}

func (x *PercentRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PercentRequest) GetPercent() float64 {
	if x != nil {
		return x.Percent
	}
	return 0
}

type PercentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           float64                `protobuf:"fixed64,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PercentResponse) Reset() {
	*x = PercentResponse{}
	mi := &file_proto_calculator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PercentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PercentResponse) ProtoMessage() {}

func (x *PercentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PercentResponse.ProtoReflect.Descriptor instead.
func (*PercentResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{11}
}

func (x *PercentResponse) GetRes() float64 {
	if x != nil {
		return x.Res
	}
	return 0
}

type RoundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int64                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundRequest) Reset() {
	*x = RoundRequest{}
	mi := &file_proto_calculator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundRequest) ProtoMessage() {}

func (x *RoundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundRequest.ProtoReflect.Descriptor instead.
func (*RoundRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{12}
}

func (x *RoundRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RoundRequest) GetY() int64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type RoundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           float64                `protobuf:"fixed64,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoundResponse) Reset() {
	*x = RoundResponse{}
	mi := &file_proto_calculator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoundResponse) ProtoMessage() {}

func (x *RoundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoundResponse.ProtoReflect.Descriptor instead.
func (*RoundResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{13}
}

func (x *RoundResponse) GetRes() float64 {
	if x != nil {
		return x.Res
	}
	return 0
}

type PowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowRequest) Reset() {
	*x = PowRequest{}
	mi := &file_proto_calculator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowRequest) ProtoMessage() {}

func (x *PowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowRequest.ProtoReflect.Descriptor instead.
func (*PowRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{14}
}

func (x *PowRequest) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PowRequest) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type PowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           float64                `protobuf:"fixed64,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PowResponse) Reset() {
	*x = PowResponse{}
	mi := &file_proto_calculator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PowResponse) ProtoMessage() {}

func (x *PowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PowResponse.ProtoReflect.Descriptor instead.
func (*PowResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{15}
}

func (x *PowResponse) GetRes() float64 {
	if x != nil {
		return x.Res
	}
	return 0
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            string                 `protobuf:"bytes,1,opt,name=op,proto3" json:"op,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_proto_calculator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{16}
}

func (x *Operation) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Operation) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type SequenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         float64                `protobuf:"fixed64,1,opt,name=start,proto3" json:"start,omitempty"`
	Operations    []*Operation           `protobuf:"bytes,2,rep,name=operations,proto3" json:"operations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequenceRequest) Reset() {
	*x = SequenceRequest{}
	mi := &file_proto_calculator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceRequest) ProtoMessage() {}

func (x *SequenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceRequest.ProtoReflect.Descriptor instead.
func (*SequenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{17}
}

func (x *SequenceRequest) GetStart() float64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *SequenceRequest) GetOperations() []*Operation {
	if x != nil {
		return x.Operations
	}
	return nil
}

type SequenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           float64                `protobuf:"fixed64,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SequenceResponse) Reset() {
	*x = SequenceResponse{}
	mi := &file_proto_calculator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SequenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SequenceResponse) ProtoMessage() {}

func (x *SequenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_calculator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SequenceResponse.ProtoReflect.Descriptor instead.
func (*SequenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_calculator_proto_rawDescGZIP(), []int{18}
}

func (x *SequenceResponse) GetRes() float64 {
	if x != nil {
		return x.Res
	}
	return 0
}

var File_proto_calculator_proto protoreflect.FileDescriptor

const file_proto_calculator_proto_rawDesc = "" +
	"\n" +
	"\x16proto/calculator.proto\"(\n" +
	"\n" +
	"AddRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\x1f\n" +
	"\vAddResponse\x12\x10\n" +
	"\x03res\x18\x01 \x01(\x01R\x03res\"(\n" +
	"\n" +
	"SubRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\x1f\n" +
	"\vSubResponse\x12\x10\n" +
	"\x03res\x18\x01 \x01(\x01R\x03res\")\n" +
	"\vMultRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\" \n" +
	"\fMultResponse\x12\x10\n" +
	"\x03res\x18\x01 \x01(\x01R\x03res\"(\n" +
	"\n" +
	"DivRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\x1f\n" +
	"\vDivResponse\x12\x10\n" +
	"\x03res\x18\x01 \x01(\x01R\x03res\"\x1b\n" +
	"\vSqrtRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\" \n" +
	"\fSqrtResponse\x12\x10\n" +
	"\x03res\x18\x01 \x01(\x01R\x03res\"8\n" +
	"\x0ePercentRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\x18\n" +
	"\apercent\x18\x02 \x01(\x01R\apercent\"#\n" +
	"\x0fPercentResponse\x12\x10\n" +
	"\x03res\x18\x01 \x01(\x01R\x03res\"*\n" +
	"\fRoundRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x03R\x01y\"!\n" +
	"\rRoundResponse\x12\x10\n" +
	"\x03res\x18\x01 \x01(\x01R\x03res\"(\n" +
	"\n" +
	"PowRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"\x1f\n" +
	"\vPowResponse\x12\x10\n" +
	"\x03res\x18\x01 \x01(\x01R\x03res\"1\n" +
	"\tOperation\x12\x0e\n" +
	"\x02op\x18\x01 \x01(\tR\x02op\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\"S\n" +
	"\x0fSequenceRequest\x12\x14\n" +
	"\x05start\x18\x01 \x01(\x01R\x05start\x12*\n" +
	"\n" +
	"operations\x18\x02 \x03(\v2\n" +
	".OperationR\n" +
	"operations\"$\n" +
	"\x10SequenceResponse\x12\x10\n" +
	"\x03res\x18\x01 \x01(\x01R\x03res2\xe5\x02\n" +
	"\n" +
	"Calculator\x12 \n" +
	"\x03Add\x12\v.AddRequest\x1a\f.AddResponse\x12 \n" +
	"\x03Sub\x12\v.SubRequest\x1a\f.SubResponse\x12#\n" +
	"\x04Mult\x12\f.MultRequest\x1a\r.MultResponse\x12 \n" +
	"\x03Div\x12\v.DivRequest\x1a\f.DivResponse\x12#\n" +
	"\x04Sqrt\x12\f.SqrtRequest\x1a\r.SqrtResponse\x12,\n" +
	"\aPercent\x12\x0f.PercentRequest\x1a\x10.PercentResponse\x12&\n" +
	"\x05Round\x12\r.RoundRequest\x1a\x0e.RoundResponse\x12 \n" +
	"\x03Pow\x12\v.PowRequest\x1a\f.PowResponse\x12/\n" +
	"\bSequence\x12\x10.SequenceRequest\x1a\x11.SequenceResponseB\x1eZ\x1cWeb-Labs/23/proto;calculatorb\x06proto3"

var (
	file_proto_calculator_proto_rawDescOnce sync.Once
	file_proto_calculator_proto_rawDescData []byte
)

func file_proto_calculator_proto_rawDescGZIP() []byte {
	file_proto_calculator_proto_rawDescOnce.Do(func() {
		file_proto_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_calculator_proto_rawDesc), len(file_proto_calculator_proto_rawDesc)))
	})
	return file_proto_calculator_proto_rawDescData
}

var file_proto_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_calculator_proto_goTypes = []any{
	(*AddRequest)(nil),       // 0: AddRequest
	(*AddResponse)(nil),      // 1: AddResponse
	(*SubRequest)(nil),       // 2: SubRequest
	(*SubResponse)(nil),      // 3: SubResponse
	(*MultRequest)(nil),      // 4: MultRequest
	(*MultResponse)(nil),     // 5: MultResponse
	(*DivRequest)(nil),       // 6: DivRequest
	(*DivResponse)(nil),      // 7: DivResponse
	(*SqrtRequest)(nil),      // 8: SqrtRequest
	(*SqrtResponse)(nil),     // 9: SqrtResponse
	(*PercentRequest)(nil),   // 10: PercentRequest
	(*PercentResponse)(nil),  // 11: PercentResponse
	(*RoundRequest)(nil),     // 12: RoundRequest
	(*RoundResponse)(nil),    // 13: RoundResponse
	(*PowRequest)(nil),       // 14: PowRequest
	(*PowResponse)(nil),      // 15: PowResponse
	(*Operation)(nil),        // 16: Operation
	(*SequenceRequest)(nil),  // 17: SequenceRequest
	(*SequenceResponse)(nil), // 18: SequenceResponse
}
var file_proto_calculator_proto_depIdxs = []int32{
	16, // 0: SequenceRequest.operations:type_name -> Operation
	0,  // 1: Calculator.Add:input_type -> AddRequest
	2,  // 2: Calculator.Sub:input_type -> SubRequest
	4,  // 3: Calculator.Mult:input_type -> MultRequest
	6,  // 4: Calculator.Div:input_type -> DivRequest
	8,  // 5: Calculator.Sqrt:input_type -> SqrtRequest
	10, // 6: Calculator.Percent:input_type -> PercentRequest
	12, // 7: Calculator.Round:input_type -> RoundRequest
	14, // 8: Calculator.Pow:input_type -> PowRequest
	17, // 9: Calculator.Sequence:input_type -> SequenceRequest
	1,  // 10: Calculator.Add:output_type -> AddResponse
	3,  // 11: Calculator.Sub:output_type -> SubResponse
	5,  // 12: Calculator.Mult:output_type -> MultResponse
	7,  // 13: Calculator.Div:output_type -> DivResponse
	9,  // 14: Calculator.Sqrt:output_type -> SqrtResponse
	11, // 15: Calculator.Percent:output_type -> PercentResponse
	13, // 16: Calculator.Round:output_type -> RoundResponse
	15, // 17: Calculator.Pow:output_type -> PowResponse
	18, // 18: Calculator.Sequence:output_type -> SequenceResponse
	10, // [10:19] is the sub-list for method output_type
	1,  // [1:10] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_calculator_proto_init() }
func file_proto_calculator_proto_init() {
	if File_proto_calculator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_calculator_proto_rawDesc), len(file_proto_calculator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_calculator_proto_goTypes,
		DependencyIndexes: file_proto_calculator_proto_depIdxs,
		MessageInfos:      file_proto_calculator_proto_msgTypes,
	}.Build()
	File_proto_calculator_proto = out.File
	file_proto_calculator_proto_goTypes = nil
	file_proto_calculator_proto_depIdxs = nil
}
